BinomeProject/BinomeProject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SystemeGestion.urls')),
]

BinomeProject/SystemeGestion/urls.py
from django.contrib import admin
from django.urls import include, path
from .import views

urlpatterns=[
    path("select2/", include("django_select2.urls")),
    path('',views.home,name='home'),
    path('achat/',views.achat,name='achat'),
    path('listeAchat/',views.liste_achats,name='liste_achats'),
    path('ModiAchat/<int:achat_id>/',views.modifier_achat,name='modifier_achat'),
    path('delete_achat/<int:achat_id>/', views.delete_achat, name='delete_achat'),
    path('saisir_montant/<int:achat_id>/', views.saisir_montant, name='saisir_montant'),
    
    path('fournisseur/',views.fournisseur,name='fournisseur'),
    path('delete_fournisseur/<int:fournisseur_id>/',views.delete_fournisseur,name='delete_fournisseur'),
    path('listeFournisseurs/',views.liste_fournisseurs,name='liste_fournisseurs'),
    path('modiFourni/<int:fournisseur_id>',views.modifier_fournisseur,name='modifier_fournisseur'),
    path('paiement/<int:fournisseur_id>/',views.reg, name='reg'),
    path('listeReglements/', views.liste_reglement,name='liste_reglement'),
    path('delete_reglement/<int:reglement_id>/',views.delete_reglement, name='delete_reglement'),

    path('matirerepr/',views.matierepremiere,name='matierepremiere'),
    path('listeMatierePre/', views.list_matierepremiere,name='list_matierepremiere'),
    path('modifMatiere/<int:produit_id>/',views.modifier_matierepremiere,name='modifier_matierepremiere'),
    path('delete_matierepr/<int:produit_id>/',views.delete_matierepremiere,name='delete_matierepremiere'),

    
    path('creer_transfert/', views.creer_transfert, name='creer_transfert'),
    path('fiche_transferts/', views.fiche_transferts, name='fiche_transfert'),
    path('fiche_transfert_centres/', views.fiche_transfert_centres, name='fiche_transfert_centres'),
    path('centres/<int:centre_id>/fiche_transferts/', views.fiche_transfert_centres, name='fiche_transfert_centres'),

    path('listeCentres/',views.liste_centres,name='liste_centres'),
    path('details_centre/<int:centre_id>/', views.details_centre, name='details_centre'),
    path('centres/<int:centre_id>/employes/', views.employes, name='employes'),
    path('centres/<int:centre_id>/list_employes/', views.list_employes, name='list_employes'),
    path('list_employes/<int:employe_id>/paiment_journalier/', views.paiment_journalier, name='paiment_journalier'),
    path('list_employes/<int:employe_id>/delete_emloyes/', views.delete_emloyes, name='delete_emloyes'),
    path('modifier_employe/<int:employe_id>/', views.modifier_employe, name='modifier_employe'),

    # path('calcul_salaire_mensuel/', views.calculer_salaire_mensuel, name='calcul_salaire_mensuel'),

    path('vente/',views.vendre,name='vente'),
    path('journalvente/',views.journal_vente,name='journal_vente'),
    path('Modivente/<int:vente_id>/',views.modifier_vente,name='modifier_vente'),
    path('suppvente/<int:vente_id>/',views.delete_vente,name='supprimer_vente'),
    
    path('Ajoutcl/',views.client,name='Ajout'),
    path('listecl/',views.listeclient,name='listeclient'),
    path('reglement/<int:vente_id>/', views.reglement, name='reglement'),
    path('liste_reglements/', views.liste_reglements, name='liste_reglements'),
    path('ModiC/<int:client_id>/',views.modifier_client,name='modifier_client'),
    path('suppC/<int:client_id>/',views.supp_client,name='supp_client'),

    path('centres/<int:centre_id>/AjoutP/',views.production,name='AjoutP'),
    path('modifP/<int:product_id>/',views.modifier_product,name='modifP'),
    path('deleteP/<int:product_id>/',views.delete_product,name='deleteP'),
    path('centres/<int:centre_id>/liste_P/', views.list_P, name='listeP'),

    path('centres/<int:centre_id>/AjoutV/',views.ventec,name='AjoutV'),
    path('centres/<int:centre_id>/listeV/', views.list_V, name='listeV'),
    path('modifV/<int:VenteC_id>/',views.modifier_V,name='modifV'),
    path('deleteV/<int:VenteC_id>/',views.delete_V,name='deleteV'),

    path('dashboard/', views.dashboard, name='dashboard'),
]

BinomeProject/SystemeGestion/models.py
from django.db import models

class Fournisseur(models.Model):
    ID_Fourni= models.AutoField(primary_key=True)
    NomF = models.CharField(max_length=200)
    adresse = models.CharField(max_length=200)
    email = models.EmailField() #remplacer par Num_Telephone
    solde = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    
    def __str__(self):
        return self.NomF


class MatierePremiere(models.Model):
    Code=models.AutoField(primary_key=True)
    NomP=models.CharField(max_length=30)
    Description=models.CharField(max_length=100)
    Qte=models.IntegerField(default=0)
    prix=models.DecimalField(max_digits=10, decimal_places=2,default=0)
    prix_vente=models.DecimalField(max_digits=10, decimal_places=2,default=0)
    def __str__(self):
        return self.NomP

    

class Achat(models.Model):
    CodeAchat=models.AutoField(primary_key=True)
    fournisseur = models.ForeignKey(Fournisseur, on_delete=models.CASCADE)
    matierePremiere = models.ForeignKey(MatierePremiere,on_delete=models.CASCADE)
    quantite = models.IntegerField()
    date_achat = models.DateField()
    prix_unitaire_ht = models.DecimalField(max_digits=10, decimal_places=2)
    montant_total_achat_ht = models.DecimalField(max_digits=10, decimal_places=2,default=0)
    montant_paye = models.DecimalField(decimal_places=2, max_digits=10,default=0)

    def __str__(self):
        return self.matierePremiere.NomP
    
    def montant_reste(self):
        return self.montant_total_achat_ht - self.montant_paye
    
class Client(models.Model):
    Code_Client=models.AutoField(primary_key=True)
    Nom=models.CharField(max_length=30)
    Prenom=models.CharField(max_length=30) #ajouter numtelphone
    Adress=models.CharField(max_length=50)
    def __str__(self):
        return str(self.Nom)

class Reglement_Fournisseur(models.Model):
    ID=models.AutoField(primary_key=True)
    fournisseur=models.ForeignKey(Fournisseur,on_delete=models.CASCADE)
    date_reglement=models.DateField()
    montant_versement=models.DecimalField(max_digits=10,decimal_places=2)

class Centre(models.Model):
    Code=models.AutoField(primary_key=True) #modifier to CodeCentre
    designation=models.CharField(max_length=100,choices=(('centre1', 'Centre 1'), ('centre2', 'Centre 2'), ('centre3', 'Centre 3')))
    def __str__(self):
        return self.designation
    
class Transfert(models.Model):
    CodeTransfert=models.AutoField(primary_key=True)
    date_transfert=models.DateField()
    centre = models.ForeignKey(Centre,on_delete=models.CASCADE)
    matierePremiere = models.ForeignKey(MatierePremiere, on_delete=models.CASCADE)
    quantite = models.IntegerField()
    cout_transfert=models.DecimalField(max_digits=10,decimal_places=2,default=0)
    total=models.DecimalField(max_digits=10,decimal_places=2,default=0)

class Employe(models.Model):
    CodeE=models.AutoField(primary_key=True)
    centre=models.ForeignKey(Centre,on_delete=models.CASCADE)
    NomE=models.CharField(max_length=100)
    AdrE=models.CharField(max_length=200)
    Email=models.EmailField()
    Tlf=models.IntegerField()
    Salaire=models.DecimalField(max_digits=10,decimal_places=2,default=0)

    def __str__(self):
        return self.NomE


class Paiement_Emloyes(models.Model):
    CodePay=models.AutoField(primary_key=True)
    employe=models.ForeignKey(Employe,on_delete=models.CASCADE)
    date_paiement=models.DateField()
    presence=models.BooleanField()
    salaire_journalier=models.DecimalField(max_digits=10,decimal_places=2,default=0)
    salaire_retenu=models.DecimalField(max_digits=10,decimal_places=2,default=0,null=True, blank=True)
    masrouf=models.DecimalField(max_digits=10,decimal_places=2,default=0,null=True, blank=True)
   
    def __str__(self):
        return str(self.CodePay)


class CreditClient(models.Model):
    CodeCredit=models.AutoField(primary_key=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    montant_vente = models.FloatField()
    montant_paye = models.FloatField()
    montant_restant = models.FloatField()        



class Vente(models.Model):
    codevente=models.AutoField(primary_key=True)
    Client = models.ForeignKey(Client, on_delete=models.CASCADE)
    mtrP = models.ForeignKey(MatierePremiere,on_delete=models.CASCADE)
    qte = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    montant_vente = models.FloatField(editable=False) # ce champ ne sera pas modifiable par l'utilisateur
    credit_client = models.ForeignKey(CreditClient, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.mtrP.NomP
    def save(self, *args, **kwargs):
        self.montant_vente= self.qte * self.price
        super().save(*args, **kwargs)


class Product(models.Model):
    CodP=models.AutoField(primary_key=True)
    centre=models.ForeignKey(Centre,on_delete=models.CASCADE)
    Nom=models.CharField(max_length=30)
    designation=models.CharField(max_length=30)
    date_production=models.DateField()
    Quantite=models.IntegerField(default=0)
    price_v=models.DecimalField(max_digits=10, decimal_places=2,default=0)
    def __str__(self):
        return self.Nom
    

class VenteC(models.Model):
    CodeVenteC=models.AutoField(primary_key=True)
    centre=models.ForeignKey(Centre,on_delete=models.CASCADE)
    Client = models.ForeignKey(Client, on_delete=models.CASCADE)
    prdt = models.ForeignKey(Product,on_delete=models.CASCADE)
    qte = models.PositiveIntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    montant_vente = models.FloatField(editable=False) # ce champ ne sera pas modifiable par l'utilisateur
    def __str__(self):
        return self.prdt.Nom
    def save(self, *args, **kwargs):
        self.montant_vente= self.qte * self.price
        super().save(*args, **kwargs)
        

BinomeProject/SystemeGestion/forms.py
from django import forms
from .models import*
import django_filters
from django.utils.translation import gettext_lazy as _
from django_select2 import forms as s2forms 

class FournisseurWidget(s2forms.ModelSelect2Widget):
    model = Fournisseur  # Ajoutez cette ligne pour spécifier le modèle
    search_fields = [
        'NomF__icontains',
    ]

class AchatForm(forms.ModelForm):
    class Meta:
        model = Achat
        fields = ['fournisseur', 'matierePremiere', 'quantite', 'prix_unitaire_ht', 'date_achat']
        labels={
            'fournisseur':_("Fournisseur :"),
            'matierePremiere':_("Matière première :"),
            'quantite':_("Quantité :"),
            'prix_unitaire_ht':_("Prix Unitaire :"),
            'date_achat':_("Date achat :"),
        }


class ModifierAchatForm(forms.ModelForm):
    class Meta:
        model = Achat
        fields = ['fournisseur', 'matierePremiere', 'quantite', 'prix_unitaire_ht', 'date_achat']
        labels = {
            'matierePremiere': _("Matière première :"),
            'quantite': _("Quantité :"),
            'prix_unitaire_ht': _("Prix Unitaire :"),
            'date_achat': _("Date achat :"),
        }
        widgets = {
            'date_achat': forms.DateInput(attrs={'type': 'date'}),
        }

class FournisseurForm(forms.ModelForm):
    class Meta:
        model = Fournisseur
        fields = ['NomF', 'adresse', 'email']    
        labels={
            'NomF':_("Nom  :"),
            'adresse':_("Adresse :"),
            'email':_("Email :"),
        }

class FournisseurFilter(django_filters.FilterSet):
    class Meta:
        model=Fournisseur
        fields= ['NomF']
        labels={
            'NomF':_("Nom Fournisseur :"),
        }

class MatierePremiereForm(forms.ModelForm):
    class Meta:
        model=MatierePremiere
        fields = ['NomP','Description']
        labels={
            'NomP':_("Nom de la matière :"),
            'Description':_("Description :"),
        }


class AchatFilter(django_filters.FilterSet):
    class Meta:
        model=Achat
        fields= ['fournisseur', 'matierePremiere','date_achat']
        labels={
            'fournisseur':_("Fournisseur :"),
            'matierePremiere':_("Matière première :"),
            'date_achat':_("Date :"),
        }
        widgets={
            'fournisseur':FournisseurWidget
        }

class TransfertFilter(django_filters.FilterSet):
    class Meta:
        model = Transfert
        fields = ['date_transfert', 'centre', 'matierePremiere']
        labels = {
            'date_transfert': _("Date du transfert :"),
            'centre': _("Centres :"),
            'matierePremiere': _("Nom de Matiere :")
        }

class VenteFilter(django_filters.FilterSet):
    class Meta:
        model=Vente
        fields=['Client','mtrP']
        labels={
            'Client':_("Client :"),
            'mtrP':_("Matiere Premiere :")
        }

class VenteCFilter(django_filters.FilterSet):
    class Meta:
        model=VenteC
        fields=['Client']
        labels={
            'Client':_("Client :"),
        }

class VenteCForm(forms.ModelForm):
    class Meta:
        model=VenteC
        fields=['Client', 'prdt'] 
        Labels={
            'Client':_("Client :"),
            'prdt':_("Produit :"),
        }

class MontantForm(forms.ModelForm):
    class Meta:
        model =Achat
        fields=['montant_paye']
        labels={
            'montant_paye':_("Montant à paye :"),
        }

class Reglement(forms.ModelForm):
    class Meta:
        model=Reglement_Fournisseur
        fields=['date_reglement','montant_versement']
        error_messages = {
            'date_reglement':{'required':''},
            'montant_versement':{'required':''}
        }
        labels={
            'date_reglement':_("Date :"),
            'montant_versement':_("Montant_versement :"),
        }

class TransfertForm(forms.ModelForm):
    class Meta:
        model = Transfert
        fields = ['date_transfert', 'centre', 'matierePremiere', 'quantite']
        labels={
            'date_transfert':_("Date :"),
            'centre':_("Centre :"),
            'matierePremiere':_("La matière:"),
            'quantite':_("Quantité transferer "),
        }

class CentreForm(forms.ModelForm):
    class Meta:
        model = Centre
        fields = ['designation']

class EmployeForm(forms.ModelForm):
    class Meta:
        model=Employe
        fields=['NomE','AdrE','Email','Tlf']
        labels={
            'NomE':_("Nom :"),
            'AdrE':_("Adresse  :"),
            'Email':_("Email:"),
            'Tlf':_("Numero de telephone "),
        }

class PaimentEmpoye(forms.ModelForm):
    class Meta:
        model=Paiement_Emloyes
        fields=['presence','date_paiement','salaire_journalier','salaire_retenu','masrouf']
        labels={
            'presence':_("Presence"),
            'date_paiement':_("Date :"),
            'salaire_journalier':_("salaire_journalier est :"),
            'salaire_retenu':_("salaire_retenu est :"),
            'masrouf':_("Valeur du masrouf donné est :"),
        }




class ClientForm(forms.ModelForm):
    class Meta:
       model = Client
       fields = ['Nom','Prenom','Adress']   
       labels={
           'Nom':_("Nom :"),
           'Prenom':_("Prenom :"),
           'Adress':_("Adress :"),
       }
   
class VenteForm(forms.ModelForm):
    class Meta:
        model =Vente
        fields = ['Client', 'mtrP', 'qte', 'price']
        labels={
           'Client':_("Client :"),
           'mtrP':_("Matiere Premiere :"),
           'qte':_("Quantité :"),
           'price':_("Prix :"),
       }

class ReglementForm(forms.Form):
    montant_paye = forms.FloatField(label='Montant Payé')
    

class ModifierVenteForm(forms.ModelForm):
    class Meta:
        model=Vente
        fields=['Client', 'mtrP', 'qte', 'price']
        labels={
           'Client':_("Client :"),
           'mtrP':_("Matiere Premiere :"),
           'qte':_("Quantité :"),
           'price':_("Prix :"),
       }


class ProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=['Nom', 'date_production','designation','Quantite','price_v']  
        Labels={
            'Nom':_("Nom :"),
            'date_production':_("Date de production :"),
            'designation':_("Designation :"),
            'Quantite':_("Quantité :"),
            'price_v':_("Prix de vente :"),  
        }  


class ModifierProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=[ 'Nom', 'date_production','designation','Quantite','price_v']
        Labels={
            'Nom':_("Nom :"),
            'date_production':_("Date de production :"),
            'designation':_("Designation :"),
            'Quantite':_("Quantité :"),
            'price_v':_("Prix de vente :"),  
        } 

class VenteCForm(forms.ModelForm):
    class Meta:
        model=VenteC
        fields=['Client', 'prdt', 'qte', 'price']   
        Labels={
            'Client':_("Client :"),
            'prdt':_("Produit :"),
            'qte':_("Quantité :"),
            'price':_("Prix :"),
        } 

class ModifierVenteC(forms.ModelForm):
    class Meta:
        model=VenteC
        fields=['Client', 'prdt', 'qte', 'price']  
        Labels={
            'Client':_("Client :"),
            'prdt':_("Produit :"),
            'qte':_("Quantité :"),
            'price':_("Prix :"),  
        } 

BinomeProject/SystemeGestion/templates/vente/AjoutClient.html
{% extends 'home1.html'%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <title>Document</title>
  </head>
  <body>
    <div class="button-container">

      <h2>Client</h2>
      <form method="post">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit" class="btn btn-outline-secondary">Enregistrer</button>
      </form>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    </div>
    </body>
</html>
{% endblock %}

BinomeProject/SystemeGestion/templates/vente/ModifierClient.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Modifier Client</title>
  </head>
  <body>
    <h2>Modifier Client</h2>
    <form method="post" action="">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Modifier Client</button>
    </form>
  </body>
</html>
{% endblock %}

BinomeProject/SystemeGestion/templates/vente/ModifierVente.html
{% extends 'home1.html'%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Modifier Vente</title>
  </head>
  <body>
    <h2>Modifier Vente</h2>
    <form method="post" action="">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Modifier Vente</button>
    </form>
  </body>
  </html>
  
  {% endblock %}

BinomeProject/SystemeGestion/templates/vente/SuppClient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

BinomeProject/SystemeGestion/templates/vente/SupprimerVente.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>le vente est bien etait supprimer</h1>
  </body>
</html>

BinomeProject/SystemeGestion/templates/vente/journal_vente.html
{% extends 'home.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <title>Document</title>
  </head>
  <body>
    <div class="button-container">
      {% if vendus %}
      <h2>Journal des ventes</h2>
      <form method="get" action="{% url 'journal_vente' %}">
        {{ myfilter.form.as_p }}
        <button type="submit" class="btn btn-outline-secondary">Rechercher</button>
     </form>
     <a href="{%url 'vente'%}"><button class="btn btn-outline-secondary">Ajouter vente</button></a>
      <table class="table table-success table-striped">
        <thead>
          <tr>
            <th>Client</th>
          <th>produit</th>
          <th>Quantite</th>
          <th>prix_unitaire</th>
          <th>Montant </th>
        </tr>
      </thead>
      <tbody>
        {% for vendre in vendus %}
        <tr>
            <td>{{ vendre.Client }}</td>
            <td>{{ vendre.mtrP }}</td>
            <td>{{ vendre.qte }}</td>
            <td>{{ vendre.price }}</td>
            <td>{{ vendre.montant_vente }}</td>
            <td>
              <form method="post" action="{% url 'modifier_vente' vente_id=vendre.codevente %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Modifier</button>
            </form>
            </td>
            <td>
              <form method="post" action="{% url 'supprimer_vente' vente_id=vendre.codevente %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Supprimer</button>
            </form>
            </td>
            <td>
              <form method="post" action="{% url 'reglement' vente_id=vendre.codevente %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-success">Reglement</button>
            </form>
            
            </td>
        </tr>
        {% endfor %}
    </tbody>  
    {% else %}
    <h1>pas de ventes</h1>
    {% endif%}
  </ul>
    <a href="{%url 'listeclient'%}" ><button class="btn btn-outline-secondary">Consulter liste clients</button></a>
</div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</html>
{% endblock %}

BinomeProject/SystemeGestion/templates/vente/liste_reglementsC.html
{% extends 'home1.html'%} {% load static %} {% block content %}
<!-- templates/liste_reglements.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AgriStock</title>
  </head>
  <body>
    <h2>Liste des Règlements</h2>
    <table border="1px">
      <thead>
        <tr>
          <th>Client</th>
          <th>Montant Payé</th>
          <th>montant_vente</th>
          <th>montant_restant</th>
        </tr>
      </thead>
      <tbody>
        {% csrf_token %} {% for reglement in reglements %}
        <tr>
          <td>{{ reglement.client }}</td>
          <td>{{ reglement.montant_paye }}</td>
          <td>{{ reglement.montant_vente }}</td>
          <td>{{ reglement.montant_restant }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

{% endblock %}

BinomeProject/SystemeGestion/templates/vente/listeclient.html
{% extends 'home1.html'%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <title>Document</title>
  </head>
  <body>
    <h2>Liste des clients</h2>
    <a href="{% url 'Ajout' %}">
      <!-- Lien vers la page Ajout Client -->
      <button type="button" class="btn btn-outline-secondary">Nouveau Client</button>
    </a>
    <table class="table table-success table-striped">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Prenom</th>
          <th>Adress</th>
        </tr>
      </thead>
      <tbody>
        {% csrf_token %} {% for client in clients %}
        <tr>
          <td>{{client.Nom}}</td>
          <td>{{client.Prenom}}</td>
          <td>{{client.Adress}}</td>
          <td>
          <form method="post" action="{% url 'modifier_client' client_id=client.Code_Client %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Modifier</button>
        </form>
        </td>
        <td>
          <form method="post" action="{% url 'supp_client' client_id=client.Code_Client %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Supprimer</button>
        </form>
        </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{%url 'liste_reglements'%}"
      ><button class="btn btn-outline-secondary">Consulter liste réglements</button></a
    >
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  </html>
  
  {% endblock %}

BinomeProject/SystemeGestion/templates/vente/reglement.html
{% extends 'home1.html'%}
{% load static %}
{% block content %}
<!-- reglement.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- ... autres balises meta ... -->
  </head>
  <body>
    <h2>Règlement de Paiement</h2>
    <p>Montant Restant : {{ credit_client.montant_restant }}</p>
    <form method="post">
      {% csrf_token %} {{ reglement_form.as_p }}
      <button type="submit">Enregistrer Paiement</button>
    </form>
  </body>
  </html>
  
  {% endblock %}

BinomeProject/SystemeGestion/templates/vente/vente.html
{% extends 'home1.html'%}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vente</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </head>
  <body>
    <h2>Vente</h2>
    <a href="{% url 'Ajout' %}">
      <!-- Lien vers la page Ajout Client -->
      <button type="button">Nouveau Client</button>
    </a>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <label for="id_montant_vente_calculé">Montant Vente Calculé:</label>
      <input
      type="text"
      id="id_montant_vente_calculé"
      name="montant_vente_calculé"
      readonly
      />
      <script>
        $(document).ready(function () {
          function calculerMontantVente() {
            var qte = parseFloat($("#id_qte").val());
            var price = parseFloat($("#id_price").val());

            if (!isNaN(qte) && !isNaN(price)) {
              var montant_vente = qte * price;
              $("#id_montant_vente_calculé").val(montant_vente.toFixed(2));
            }
          }
          
          // Appeler la fonction lors du chargement de la page
          calculerMontantVente();
          
          // Appeler la fonction à chaque changement de quantité ou de prix
          $("#id_qte, #id_price").change(function () {
            calculerMontantVente();
          });
        });
        </script>

<button type="submit">Enregistrer</button>
</form>
</body>
</html>

{% endblock %}